(function(){var l=[],t=0;window.generate_the_wcmp=function(m){function q(a){let d=a.closest(".wcmp-single-player"),b=d.find(".wcmp-first-player");c("audio").each(function(){this.pause();this.currentTime=0});d.find(".wcmp-player-container:not(.wcmp-first-player)").hide();a.hasClass(".wcmp-first-player")||(a.show().offset(b.offset()).outerWidth(b.outerWidth()),a.find("audio")[0].play())}function h(a,d){if(a+1<t||d){var b=a+1;!d||b!=t&&c('[playernumber="'+b+'"]').closest("[data-loop]").length!=0&&c('[playernumber="'+
b+'"]').closest("[data-loop]")[0]==c('[playernumber="'+a+'"]').closest("[data-loop]")[0]||(b=c('[playernumber="'+a+'"]').closest("[data-loop]").find("[playernumber]:first").attr("playernumber"));l[b]instanceof c&&l[b].is("a")?l[b].closest(".wcmp-single-player").length?q(l[b].closest(".wcmp-player-container")):l[b].is(":visible")?l[b].trigger("click"):h(a+1,d):c(l[b].domNode).closest(".wcmp-single-player").length?q(c(l[b].domNode).closest(".wcmp-player-container")):c(l[b].domNode).closest(".wcmp-player-container").is(":visible")?
l[b].domNode.play():h(a+1,d)}}function v(a){var d=a.data("product");c('[data-product="'+d+'"]').each(function(){var b=c(this).closest(".product"),f=b.find("img.product-"+d);if(f.length&&b.closest(".wcmp-player-list").length==0&&b.find(".wcmp-player-list").length==0){var n=f.offset();b=b.find("div.wcmp-player");b.length&&b.css({position:"absolute","z-index":999999}).offset({left:n.left+(f.width()-b.width())/2,top:n.top+(f.height()-b.height())/2})}})}if(!(typeof m!=="boolean"&&typeof wcmp_global_settings!=
"undefined"&&wcmp_global_settings.onload*1)&&"undefined"===typeof generated_the_wcmp){generated_the_wcmp=!0;var c=jQuery;c(".wcmp-player-container").on("click","*",function(a){a.preventDefault();a.stopPropagation();return!1}).parent().removeAttr("title");c.expr.pseudos.regex=function(a,d,b){d=b[3].split(",");var f=/^(data|css):/;b=d[0].match(f)?d[0].split(":")[0]:"attr";f=d.shift().replace(f,"");return(new RegExp(d.join("").replace(/^\s+|\s+$/g,""),"ig")).test(c(a)[b](f))};(function(){c(".wcmp-player-visualizer").each(function(){function a(){if(k){k.getByteFrequencyData(w);
var u=w.length;for(let p=0;p<32;p++){var D=Math.floor((50+p/32*11950)/(g.sampleRate/2)*u),A=Math.min(u-1,Math.floor((50+(p+1)/32*11950)/(g.sampleRate/2)*u));let F=0,E=0;for(;D<=A;D++)F+=w[D],E++;A=E?F/E:0;A*=Math.pow(p/32,1.4)*1.5+.7;B[p]=B[p]*.75+A*.25;const G=Math.min(1,B[p]/255),K=G*(f.clientHeight-10);[e[31-p],e[32+p]].forEach(function(H){H.style.height=Math.max(0,K)+"px";H.style.opacity=.3+G*.8})}y=requestAnimationFrame(a)}}function d(){y&&(cancelAnimationFrame(y),y=null,e.forEach(function(u){u.style.height=
"0"}))}var b=c(this);if(!b.data("processed")){b.data("processed",1);c(this).append('<div class="wcmp-player-visualizer-bars-container"></div>');var f=c(this).find(".wcmp-player-visualizer-bars-container")[0],n=c(this).next("audio")[0];for(b=0;b<64;b++){const u=document.createElement("div");u.className="wcmp-player-visualizer-bar";f.appendChild(u)}var e=Array.from(f.children),g,k,x,w,B,y=null;n.addEventListener("play",function(){g||(g=new (window.AudioContext||window.webkitAudioContext),k=g.createAnalyser(),
k.fftSize=2048,k.smoothingTimeConstant=.6,x=g.createMediaElementSource(n),x.connect(k),k.connect(g.destination),w=new Uint8Array(k.frequencyBinCount),B=(new Float32Array(32)).fill(0));g.state==="suspended"&&g.resume();y||a()});n.addEventListener("pause",d);n.addEventListener("ended",d)}})})();var z=typeof wcmp_global_settings!="undefined"?wcmp_global_settings.play_all:!0,r=typeof wcmp_global_settings!="undefined"?!(wcmp_global_settings.play_simultaneously*1):!0,I=typeof wcmp_global_settings!="undefined"?
wcmp_global_settings.fade_out*1:!0,J=typeof wcmp_global_settings!="undefined"&&"ios_controls"in wcmp_global_settings&&wcmp_global_settings.ios_controls*1?!0:!1;m=c("audio.wcmp-player:not(.track):not([playernumber])");var L=c("audio.wcmp-player.track:not([playernumber])"),C={pauseOtherPlayers:r,iPadUseNativeControls:J,iPhoneUseNativeControls:J,success:function(a,d){var b=c(d).data("duration"),f=c(d).data("estimated_duration"),n=c(d).attr("playernumber");typeof f!="undefined"&&(a.getDuration=function(){return f});
typeof b!="undefined"&&setTimeout(function(e,g){return function(){l[e].updateDuration=function(){c(this.media).closest(".wcmp-player").find(".mejs-duration").html(g)};l[e].updateDuration()}}(n,b),50);c(d).attr("volume")&&(a.setVolume(parseFloat(c(d).attr("volume"))),a.volume==0&&a.setMuted(!0));a.addEventListener("playing",function(e){var g=c(a),k=g.closest(".wcmp-single-player");try{let x=c(e.detail.target).attr("data-product");if(typeof x!="undefined"){let w=window.location.protocol+"//"+window.location.host+
"/"+window.location.pathname.replace(RegExp("^/","g"),"").replace(RegExp("/$","g"),"")+"?wcmp-action=play&wcmp-product="+x;c.get(w)}}catch(x){}k.length&&(e=g.closest(".wcmp-player-container").attr("data-wcfm-pair"),k.find('.wcmp-player-title[data-wcfm-pair="'+e+'"]').addClass("wcmp-playing"))});a.addEventListener("timeupdate",function(e){e=a.getDuration();isNaN(a.currentTime)||isNaN(e)||(I&&e-a.currentTime<4?a.setVolume(a.volume-a.volume/3):a.currentTime&&(typeof a.bkVolume=="undefined"&&(a.bkVolume=
parseFloat(c(a).find("audio,video").attr("volume")||a.volume)),a.setVolume(a.bkVolume),a.bkVolume==0&&a.setMuted(!0)))});a.addEventListener("volumechange",function(e){e=a.getDuration();isNaN(a.currentTime)||isNaN(e)||!(e-a.currentTime>4)&&I||!a.currentTime||(a.bkVolume=a.volume)});a.addEventListener("ended",function(e){e=c(a);var g=e.closest('[data-loop="1"]');e[0].currentTime=0;e.closest(".wcmp-single-player").length&&e.closest(".wcmp-single-player").find(".wcmp-playing").removeClass("wcmp-playing");
if(z*1||g.length){var k=e.attr("playernumber")*1;isNaN(k)&&(k=e.find("[playernumber]").attr("playernumber")*1);h(k,g.length)}})}};r=".product-type-grouped :regex(name,quantity\\[\\d+\\])";m.each(function(){var a=c(this);a.find("source").attr("src");a.attr("playernumber",t);C.audioVolume="vertical";try{l[t]=new MediaElementPlayer(a[0],C)}catch(d){"console"in window&&console.log(d)}t++});L.each(function(){var a=c(this);a.find("source").attr("src");a.attr("playernumber",t);C.features=["playpause"];try{l[t]=
new MediaElementPlayer(a[0],C)}catch(d){"console"in window&&console.log(d)}t++;v(a);c(window).on("resize",function(){v(a)})});c(r).length||(r=".product-type-grouped [data-product_id]");c(r).length||(r=".woocommerce-grouped-product-list [data-product_id]");c(r).length||(r='.woocommerce-grouped-product-list [id*="product-"]');c(r).each(function(){try{var a=c(this),d=(a.data("product_id")||a.attr("name")||a.attr("id")).replace(/[^\d]/g,""),b=c(".wcmp-player-list.merge_in_grouped_products .product-"+
d+":first .wcmp-player-title"),f=c("<table></table>");b.length&&!b.closest(".wcmp-first-in-product").length&&(b.closest("tr").addClass("wcmp-first-in-product"),b.closest("form").length==0&&b.closest(".wcmp-player-list").prependTo(a.closest("form")),f.append(a.closest("tr").prepend("<td>"+b.html()+"</td>")),b.html("").append(f))}catch(n){}});c(document).on("click","[data-wcfm-pair]",function(){let a=c(this),d=a.closest(".wcmp-single-player"),b;d.length&&(c(".wcmp-player-title").removeClass("wcmp-playing"),
b=a.attr("data-wcfm-pair"),a.addClass("wcmp-playing"),q(d.find('.wcmp-player-container[data-wcfm-pair="'+b+'"]')))})}};window.wcmp_force_init=function(){delete window.generated_the_wcmp;generate_the_wcmp(!0)};jQuery(generate_the_wcmp);jQuery(window).on("load",function(){generate_the_wcmp(!0);var m=jQuery,q=window.navigator.userAgent;m("[data-lazyloading]").each(function(){var h=m(this);h.attr("preload",h.data("lazyloading"))});if(q.match(/iPad/i)||q.match(/iPhone/i))if(typeof wcmp_global_settings!=
"undefined"?wcmp_global_settings.play_all:1)m(".wcmp-player .mejs-play button").one("click",function(){if("undefined"==typeof wcmp_preprocessed_players){wcmp_preprocessed_players=!0;var h=m(this);m(".wcmp-player audio").each(function(){this.play();this.pause()});setTimeout(function(){h.trigger("click")},500)}})}).on("popstate",function(){jQuery("audio[data-product]:not([playernumber])").length&&wcmp_force_init()});(new MutationObserver(function(m){let q=!1;for(let v=0;v<m.length;v++){let c=m[v];if(c.type===
"childList"&&c.addedNodes.length>0)for(let z=0;z<c.addedNodes.length;z++){var h=c.addedNodes[z];h=h.nodeType===Node.ELEMENT_NODE?h.tagName==="AUDIO"&&h.classList&&h.classList.contains("wcmp-player")?!0:h.querySelectorAll("audio.wcmp-player").length>0:!1;h&&(q=!0)}}q&&wcmp_force_init()})).observe(document,{childList:!0,subtree:!0})})();
