(function(){var h=[],n=0;window.generate_the_wcmp=function(k){function l(a){let d=a.closest(".wcmp-single-player"),b=d.find(".wcmp-first-player");c("audio").each(function(){this.pause();this.currentTime=0});d.find(".wcmp-player-container:not(.wcmp-first-player)").hide();a.hasClass(".wcmp-first-player")||(a.show().offset(b.offset()).outerWidth(b.outerWidth()),a.find("audio")[0].play())}function f(a,d){if(a+1<n||d){var b=a+1;!d||b!=n&&c('[playernumber="'+b+'"]').closest("[data-loop]").length!=0&&c('[playernumber="'+
b+'"]').closest("[data-loop]")[0]==c('[playernumber="'+a+'"]').closest("[data-loop]")[0]||(b=c('[playernumber="'+a+'"]').closest("[data-loop]").find("[playernumber]:first").attr("playernumber"));h[b]instanceof c&&h[b].is("a")?h[b].closest(".wcmp-single-player").length?l(h[b].closest(".wcmp-player-container")):h[b].is(":visible")?h[b].trigger("click"):f(a+1,d):c(h[b].domNode).closest(".wcmp-single-player").length?l(c(h[b].domNode).closest(".wcmp-player-container")):c(h[b].domNode).closest(".wcmp-player-container").is(":visible")?
h[b].domNode.play():f(a+1,d)}}function q(a){var d=a.data("product");c('[data-product="'+d+'"]').each(function(){var b=c(this).closest(".product"),g=b.find("img.product-"+d);if(g.length&&b.closest(".wcmp-player-list").length==0&&b.find(".wcmp-player-list").length==0){var t=g.offset();b=b.find("div.wcmp-player");b.length&&b.css({position:"absolute","z-index":999999}).offset({left:t.left+(g.width()-b.width())/2,top:t.top+(g.height()-b.height())/2})}})}if(!(typeof k!=="boolean"&&typeof wcmp_global_settings!=
"undefined"&&wcmp_global_settings.onload*1)&&"undefined"===typeof generated_the_wcmp){generated_the_wcmp=!0;var c=jQuery;c(".wcmp-player-container").on("click","*",function(a){a.preventDefault();a.stopPropagation();return!1}).parent().removeAttr("title");c.expr.pseudos.regex=function(a,d,b){d=b[3].split(",");var g=/^(data|css):/;b=d[0].match(g)?d[0].split(":")[0]:"attr";g=d.shift().replace(g,"");return(new RegExp(d.join("").replace(/^\s+|\s+$/g,""),"ig")).test(c(a)[b](g))};var u=typeof wcmp_global_settings!=
"undefined"?wcmp_global_settings.play_all:!0,m=typeof wcmp_global_settings!="undefined"?!(wcmp_global_settings.play_simultaneously*1):!0,x=typeof wcmp_global_settings!="undefined"?wcmp_global_settings.fade_out*1:!0,y=typeof wcmp_global_settings!="undefined"&&"ios_controls"in wcmp_global_settings&&wcmp_global_settings.ios_controls*1?!0:!1;k=c("audio.wcmp-player:not(.track):not([playernumber])");var z=c("audio.wcmp-player.track:not([playernumber])"),v={pauseOtherPlayers:m,iPadUseNativeControls:y,iPhoneUseNativeControls:y,
success:function(a,d){var b=c(d).data("duration"),g=c(d).data("estimated_duration"),t=c(d).attr("playernumber");typeof g!="undefined"&&(a.getDuration=function(){return g});typeof b!="undefined"&&setTimeout(function(e,p){return function(){h[e].updateDuration=function(){c(this.media).closest(".wcmp-player").find(".mejs-duration").html(p)};h[e].updateDuration()}}(t,b),50);c(d).attr("volume")&&(a.setVolume(parseFloat(c(d).attr("volume"))),a.volume==0&&a.setMuted(!0));a.addEventListener("playing",function(e){var p=
c(a),r=p.closest(".wcmp-single-player");try{let w=c(e.detail.target).attr("data-product");if(typeof w!="undefined"){let A=window.location.protocol+"//"+window.location.host+"/"+window.location.pathname.replace(RegExp("^/","g"),"").replace(RegExp("/$","g"),"")+"?wcmp-action=play&wcmp-product="+w;c.get(A)}}catch(w){}r.length&&(e=p.closest(".wcmp-player-container").attr("data-wcfm-pair"),r.find('.wcmp-player-title[data-wcfm-pair="'+e+'"]').addClass("wcmp-playing"))});a.addEventListener("timeupdate",
function(e){e=a.getDuration();isNaN(a.currentTime)||isNaN(e)||(x&&e-a.currentTime<4?a.setVolume(a.volume-a.volume/3):a.currentTime&&(typeof a.bkVolume=="undefined"&&(a.bkVolume=parseFloat(c(a).find("audio,video").attr("volume")||a.volume)),a.setVolume(a.bkVolume),a.bkVolume==0&&a.setMuted(!0)))});a.addEventListener("volumechange",function(e){e=a.getDuration();isNaN(a.currentTime)||isNaN(e)||!(e-a.currentTime>4)&&x||!a.currentTime||(a.bkVolume=a.volume)});a.addEventListener("ended",function(e){e=c(a);
var p=e.closest('[data-loop="1"]');e[0].currentTime=0;e.closest(".wcmp-single-player").length&&e.closest(".wcmp-single-player").find(".wcmp-playing").removeClass("wcmp-playing");if(u*1||p.length){var r=e.attr("playernumber")*1;isNaN(r)&&(r=e.find("[playernumber]").attr("playernumber")*1);f(r,p.length)}})}};m=".product-type-grouped :regex(name,quantity\\[\\d+\\])";k.each(function(){var a=c(this);a.find("source").attr("src");a.attr("playernumber",n);v.audioVolume="vertical";try{h[n]=new MediaElementPlayer(a[0],
v)}catch(d){"console"in window&&console.log(d)}n++});z.each(function(){var a=c(this);a.find("source").attr("src");a.attr("playernumber",n);v.features=["playpause"];try{h[n]=new MediaElementPlayer(a[0],v)}catch(d){"console"in window&&console.log(d)}n++;q(a);c(window).on("resize",function(){q(a)})});c(m).length||(m=".product-type-grouped [data-product_id]");c(m).length||(m=".woocommerce-grouped-product-list [data-product_id]");c(m).length||(m='.woocommerce-grouped-product-list [id*="product-"]');c(m).each(function(){try{var a=
c(this),d=(a.data("product_id")||a.attr("name")||a.attr("id")).replace(/[^\d]/g,""),b=c(".wcmp-player-list.merge_in_grouped_products .product-"+d+":first .wcmp-player-title"),g=c("<table></table>");b.length&&!b.closest(".wcmp-first-in-product").length&&(b.closest("tr").addClass("wcmp-first-in-product"),b.closest("form").length==0&&b.closest(".wcmp-player-list").prependTo(a.closest("form")),g.append(a.closest("tr").prepend("<td>"+b.html()+"</td>")),b.html("").append(g))}catch(t){}});c(document).on("click",
"[data-wcfm-pair]",function(){let a=c(this),d=a.closest(".wcmp-single-player"),b;d.length&&(c(".wcmp-player-title").removeClass("wcmp-playing"),b=a.attr("data-wcfm-pair"),a.addClass("wcmp-playing"),l(d.find('.wcmp-player-container[data-wcfm-pair="'+b+'"]')))})}};window.wcmp_force_init=function(){delete window.generated_the_wcmp;generate_the_wcmp(!0)};jQuery(generate_the_wcmp);jQuery(window).on("load",function(){generate_the_wcmp(!0);var k=jQuery,l=window.navigator.userAgent;k("[data-lazyloading]").each(function(){var f=
k(this);f.attr("preload",f.data("lazyloading"))});if(l.match(/iPad/i)||l.match(/iPhone/i))if(typeof wcmp_global_settings!="undefined"?wcmp_global_settings.play_all:1)k(".wcmp-player .mejs-play button").one("click",function(){if("undefined"==typeof wcmp_preprocessed_players){wcmp_preprocessed_players=!0;var f=k(this);k(".wcmp-player audio").each(function(){this.play();this.pause()});setTimeout(function(){f.trigger("click")},500)}})}).on("popstate",function(){jQuery("audio[data-product]:not([playernumber])").length&&
wcmp_force_init()});(new MutationObserver(function(k){let l=!1;for(let q=0;q<k.length;q++){let c=k[q];if(c.type==="childList"&&c.addedNodes.length>0)for(let u=0;u<c.addedNodes.length;u++){var f=c.addedNodes[u];f=f.nodeType===Node.ELEMENT_NODE?f.tagName==="AUDIO"&&f.classList&&f.classList.contains("wcmp-player")?!0:f.querySelectorAll("audio.wcmp-player").length>0:!1;f&&(l=!0)}}l&&wcmp_force_init()})).observe(document,{childList:!0,subtree:!0})})();
